services:
  - type: web
    name: wabiskills-seminar-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://wabiskills-seminar.onrender.com/api
